name: Tst

on:
  push:
    branches: [ tst_ci ]
    tags:
      - '*'
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  # Increase this value to reset cache if environment.yml has not changed
  CONDA_CACHE_NUMBER: 0
  # Increase this value to reset cache if emscripten_version has not changed
  EMSDK_CACHE_FOLDER: 'emsdk-cache'
  EMSDK_CACHE_NUMBER: 0
  CCACHE_DIR: /tmp/.ccache
  CCACHE_CACHE_NUMBER: 0
  FORCE_COLOR: 3

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        test-config: [
          {runner: selenium, runtime: chrome, runtime-version: 134 },
#          {runner: selenium, runtime: firefox, runtime-version: "136.0" },
        ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          activate-environment: pyodide-env
          conda-remove-defaults: true
          channels: conda-forge

      - name: Get Date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Update environment
        run:
          mamba env update -n pyodide-env -f environment.yml

      - name: Install latest pyodide-build and build dependencies
        run : |
          which python
          ./tools/prepare_pyodide_build.sh

      - name: Install emscripten
        run: |
          python tools/install_and_patch_emscripten.py

      - name: Build recipes (imgui bundle)
        run: |
          export PIP_CONSTRAINT=$(pwd)/tools/constraints.txt
          source emsdk/emsdk_env.sh
          mkdir -p result
          pyodide build-recipes numpy typing-extensions pydantic munch imgui-bundle --install --install-dir=./dist --log-dir=build-logs | tee result/build_output.log

      - uses: pyodide/pyodide-actions/install-browser@v2
        with:
          runner: ${{ matrix.test-config.runner }}
          browser: ${{ matrix.test-config.runtime }}
          browser-version: ${{ matrix.test-config.runtime-version }}

      - name: Install test dependencies
        run: |
          which python
          echo y | python -m pip install -r requirements.txt

#      - name: Setup interactive tmate session
#        uses: mxschmitt/action-tmate@v3

      - name: Run tests
        run: |
          pytest -v -rs \
            --dist-dir=./dist/ \
            -n $(nproc) \
            --runner=${{ matrix.test-config.runner }} \
            --rt ${{ matrix.test-config.runtime }} \
            packages/imgui-bundle


#  pytest -v -rs --dist-dir=./repodata/ -n 1 --runner=selenium --rt chrome packages/imgui-bundle
#  pyodide build-recipes numpy typing-extensions pydantic munch imgui-bundle --install --install-dir=./dist --log-dir=build-logs | tee result/build_output.log
